#!/bin/bash
FILE=gamecard
echo "Compiling & Executing with Valgrind:"
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=helgrind --log-file=b.out ./$FILE 
fi
echo "Finished executing with Valgrind."